config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :contractors
  root to: 'home#index'


  resources :categories do
    resources :contractors, only: [:index]
  end

  resources :contractors, only: [:show, :edit, :update] do
    resources :estimates, only: [:new, :create]
  end

  resources :service_orders, only: [:show] do
    resources :user_reviews, only: [:new, :create]
  end

  resources :users, only: [:show]

  resources :estimates, only: [:index, :show, :edit, :update] do
    member do
      post :approve
    end
  end
  resources :service_orders, only: [:show] do
    resources :contractor_reviews
  end

end

app/models/estimate.rb
class Estimate < ApplicationRecord
  enum status: [:requested, :approved_contractor, :approved_user, :rejected_user ]
  
  belongs_to :contractor
  belongs_to :user
  has_many :service_orders

  has_one_attached :photo
  validates :description, :location, :service_date, :day_shift, presence: true
  
  def total_fee
    if self.material_fee
      self.material_fee + self.visit_fee + self.service_fee
    else
      0
    end 
  end

end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @estimates = logged.estimates
  end
  
  def new
    @contractor = Contractor.find(params[:contractor_id])
    @estimate = Estimate.new
  end

  def create
    @contractor = Contractor.find(params[:contractor_id])
    @estimate = @contractor.estimates.build(estimate_params)
    @estimate.user = current_user
    if @estimate.save
      @estimate.requested!
      flash[:message] = 'Sua solicitação foi enviada - Aguarde retorno do prestador de serviços'
      ContractorsMailer.notify_new_estimate(@contractor.id, @estimate.id)
      redirect_to @contractor
    else
      render :new
    end
  end

  def show
    @estimate = Estimate.find(params[:id])
    if contractor_signed_in? && @estimate.contractor != current_contractor
      redirect_to root_path
    end
    if user_signed_in? && !@estimate.requested_by(current_user)
      redirect_to root_path
    end
  end

  def edit
    @estimate = Estimate.find(params[:id])
  end

  def update
    @estimate = Estimate.find(params[:id])
    parameters = contractor_params if current_contractor
    @estimate.approved_contractor!
    if @estimate.update(parameters)
      EstimatesMailer.notify_estimate_response(@estimate.id)
      redirect_to @estimate
    end
  end
  
  def approve
    @estimate = Estimate.find(params[:id])
    @estimate.approved_user!
    @estimate.save
    flash[:approved_user] = t(:estimate_approved_by_user)
    redirect_to @estimate
  end

  private

  def logged
    current_user || current_contractor 
  end

  def contractor_params
    params.require(:estimate).permit(:total_hours, :visit_fee, :material_fee, :material_list, :service_fee)
  end

  def estimate_params
    params.require(:estimate).permit(:description,
      :location, :service_date, :day_shift, :photo)
  end
end

app/views/estimates/_estimate.html.erb
<h1><%= "##{estimate.id} - #{estimate.title}" %></h1>
<p>Descrição: <%= estimate.description %></p>
<p>Local: <%= estimate.location %></p>
<p>Data: <%= estimate.service_date %></p>
<p>Turno: <%= estimate.day_shift %></p>
<p>Enviado para: <%= estimate.contractor.name %></p>
<p>Solicitado por: <%= estimate.user.name %></p>

<h2> Orçamento </h2> 
<% if estimate.requested? %>
  <p>Status: Solicitado pelo Usuário</p>
<% end %>
<% if estimate.approved_contractor? %>
  <p>Status: Aguardando aprovação do usuário</p>
  <p>Tempo de Execução: <%= "#{estimate.total_hours} horas" %></p>
  <p>Custo do Material: <%= number_to_currency(estimate.material_fee) %></p>
  <p>Taxa de Visita: <%= number_to_currency(estimate.visit_fee) %></p>
  <p>Custo do Serviço: <%= number_to_currency(estimate.service_fee) %></p>
  <p>Lista de Materiais: <%= estimate.material_list %></p>
  <p>Valor Total: <%= number_to_currency(estimate.total_fee) %></p>
<% end %>

app/views/estimates/edit.html.erb
<%= render @estimate %>

<%= form_for(@estimate) do |f| %>
  <%= f.label :total_hours, 'Tempo de Execução' %>
  <%= f.number_field :total_hours %>
  <%= f.label :material_fee, 'Custo do Material' %>
  <%= f.number_field :material_fee, step: 0.5 %>
  <%= f.label :visit_fee, 'Taxa de Visita' %>
  <%= f.number_field :visit_fee, step: 0.5 %>
  <%= f.label :service_fee, 'Custo do Serviço' %>
  <%= f.number_field :service_fee, step: 0.5 %>
  <%= f.label :material_list, 'Lista de Materiais' %>
  <%= f.text_area :material_list %>
  <%= f.submit 'Enviar Orçamento' %>
<% end %>

app/views/estimates/index.html.erb
<h1>Meus Orçamentos</h1>
<ul>
  <% @estimates.each do |estimate| %>
    <li>
      <h2><%= link_to "##{estimate.id} - #{estimate.title}", estimate %></h2>
    </li>
  <% end %>
</ul>

app/views/estimates/new.html.erb
<% if @estimate.errors.any? %>
  <p>Erro ao enviar solicitação</p>
<% end %>

<h1>Novo Orçamento</h1>
<%= form_for([@contractor, @estimate]) do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location , class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :service_date %>
    <%= f.text_field :service_date , class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :day_shift %>
    <%= f.select :day_shift, options_for_select([[t(:morning)], [t(:afternoon)], [t(:evening)]]) %>
  </div>
  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <%= f.submit t(:submit_estimate), class: 'btn btn-primary' %>
<% end %>

app/views/estimates/show.html.erb
<%= render @estimate %>

<% if contractor_signed_in? %>
  <% if @estimate.requested? %>
    <%= link_to 'Responder Orçamento', edit_estimate_path %>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <%= flash[:approved_user] %>
  <% if @estimate.approved_contractor? %>
    <%= link_to 'Aprovar Orçamento', approve_estimate_path, method: :post %>
  <% end %>
<% end %>