config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :contractors
  root to: 'home#index'


  resources :categories do
    resources :contractors, only: [:index]
  end

  resources :contractors, only: [:show, :edit, :update] do
    resources :estimates, only: [:new, :create]
  end

  resources :service_orders, only: [:show] do
    resources :user_reviews, only: [:new, :create]
  end

  resources :users, only: [:show]

  resources :estimates, only: [:index, :show, :edit, :update] do
    member do
      post :approve
    end
  end
  resources :service_orders, only: [:show] do
    resources :contractor_reviews
  end

end

app/models/contractor.rb
class Contractor < ApplicationRecord
  belongs_to :category
  has_many :estimates
  has_many :service_orders, through: :estimates
  has_many :contractor_reviews, through: :service_orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :cpf, :category_id, presence: true

  has_one :profile
  accepts_nested_attributes_for :profile

  before_create do
    build_profile
  end

  def update_average
    self.average = contractor_reviews.any? ? calculate_average : 0
  end

  private

  def calculate_average
    (self.contractor_reviews.sum(:rating) / self.contractor_reviews.count).to_f
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :contractor
  
  has_many :profile_sub_categories
  has_many :sub_categories, through: :profile_sub_categories
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @contractors = @category.contractors
  end

  def show
    @contractor = Contractor.find(params[:id])
  end

  def edit
    @contractor = current_contractor
    @contractor.profile ||= @contractor.build_profile
  end

  def update
    @contractor = Contractor.find(params[:id])
    if @contractor.update(contractor_params)
      @contractor.profile.sub_categories = sub_categories_params
      redirect_to @contractor
    else
      render :edit
    end
  end

  private

  def contractor_params
    params.require(:contractor).permit(:name, :email, :cpf, profile_attributes: [:id, :city])
  end

  def sub_categories_params
    SubCategory.where(id: params[:contractor][:profile_attributes][:sub_category_ids])
  end
end

app/views/contractors/edit.html.erb
<h2>Edit Contractor</h2>

<% if @contractor.errors.full_messages.present? %>
  <p><strong> Não foi possível atualizar a conta! </strong></p>
  <% @contractor.errors.full_messages.each do |message| %>
   <p> <%= message %> </p>
  <% end %>
<% end%>

<%= form_for @contractor, url: contractor_path(@contractor), method: :patch do |f| %>
  <%= f.label :name, 'Nome: ' %>
  <%= f.text_field :name %> <br />
  <%= f.label :email, 'E-mail: ' %>
  <%= f.text_field :email %> <br />
  <%= f.label :cpf, 'CPF: ' %>
  <%= f.text_field :cpf %> <br />
  <%= f.fields_for :profile do |form_profile| %>
    <%= form_profile.label :city, 'Cidade: ' %>
    <%= form_profile.text_field :city %> <br />
    <%= form_profile.collection_check_boxes(:sub_category_ids, @contractor.category.sub_categories, :id, :name) %> <br />
  <% end %>

  <%= f.submit 'Atualizar' %>
<% end %>

app/views/contractors/index.html.erb
<h1><%= @category.name %></h1>

<div>
  <%= link_to 'Editar Categoria', edit_category_path(@category) %>
</div>

<h1>Prestadores de Serviço</h1>
<ul>
  <% @contractors.each do |contractor| %>
    <li>
      <p><%= contractor.name %></p>
      <small><%= contractor.category.name %></small>
    </li>
  <% end %>
</ul>

<% if @category.contractors.empty? %>
      <%= link_to 'Excluir Categoria', category_path(@category), method: :delete %>
    
<% end %>

app/views/contractors/show.html.erb
<% if flash[:message] %>
  <p><%= flash[:message] %></p>
<% end %>

<p><%= @contractor.name %></p>
<p><%= @contractor.email %></p>
<p><%= @contractor.cpf %></p>
<p><%= @contractor&.profile&.city %></p>

<% @contractor.profile.sub_categories.each do |sub_category| %>
  <p><%= sub_category.name %></p>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'Solicitar orçamento', new_contractor_estimate_path(@contractor) %>
<% end %>

<%= link_to 'Atualizar Perfil', edit_contractor_path(@contractor) %>

<% @contractor.contractor_reviews.each do |review|  %>
  <div>
    <p><%= review.rating %></p>
    <p><%= review.comment %></p>
  </div>
<% end %>