config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :contractors
  root to: 'home#index'


  resources :categories do
    resources :contractors, only: [:index]
  end

  resources :contractors, only: [:show, :edit, :update] do
    resources :estimates, only: [:new, :create]
  end

  resources :service_orders, only: [:show] do
    resources :user_reviews, only: [:new, :create]
  end

  resources :users, only: [:show]

  resources :estimates, only: [:index, :show, :edit, :update] do
    member do
      post :approve
    end
  end
  resources :service_orders, only: [:show] do
    resources :contractor_reviews
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :contractors
  has_many :sub_categories
  
  validates :name, presence: {message: 'Nome não pode ser vazio'}
  validates :name, uniqueness: {message: 'Já existe uma categoria com este nome'}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
  

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.name = params[:category][:name]
    if @category.save
      redirect_to category_contractors_path(@category)
    else
      render :edit
    end
  end
  

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
    flash[:message] = 'Categoria excluida com sucesso' 
    
  end

end

app/views/categories/edit.html.erb
<% if @category.errors.any? %>
  <p>Não foi possível editar a categoria</p>
  <% @category.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_for @category do |f| %>
  
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>

  <%= f.submit 'Enviar' %>

<% end %>

app/views/categories/index.html.erb
<h1> Categorias </h1>

<% if flash[:message] %>
  <p><%= flash[:message] %></p>
<% end %>

<p><%= link_to 'Nova Categoria', new_category_path %></p>
<ul>
 <%= @categories.each do |category| %>
    <li> 
    <%= link_to category.name, category_contractors_path(category) %>
</li> 
<% end %>
</ul>

app/views/categories/new.html.erb
<ul>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
</ul>
<%= form_for @category do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>